# -*- coding: utf-8 -*-
"""Data Preparation and overall analysis .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1bAht-eGQcdThPJvzoZXK1U3_JESXGC
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

dataset=pd.read_csv('/content/Dataset (1).csv')

"""

```
# This is formatted as code
```

# **understanding/cleaning data** (almost the data is already cleaned)

* based on eyes the data is well cleaned already no weirdness in data is observed

1) messy data(quality of data)
    1. REVIEW RATING - missing values
2) dirty data(due to orientation)-no such type of data is there
    1. bi weekly and fortnightly representing differently
    2. quaterly and 3 months are represented differently
    3. promo and discount are identical columns(means at all places where we have promo their we also have discount aswell.






"""

dataset.head()

dataset.sample(5)

dataset.info()
# all the columns are non null
# the type of each fields is correct
# review rating columns has some missing values-use missing values

dataset.duplicated().sum()
dataset['Customer ID'].duplicated().sum()
# none of the rows is duplicated

# now check for each stastical parameter
dataset.describe()

# understanding the review columns (null)
dataset['Review Rating'].isnull().mean()*100
# since the null values is only 1 percent of our total data we can remove it without affecting the distribution of the data
# if i would have imputed it ,it may would have affected my overall satisfaction values

cleaned_dataset = dataset.dropna(subset=['Review Rating'])

cleaned_dataset.info()

# understanding the core of data distribution

ax = cleaned_dataset['Review Rating'].plot(
    kind='kde',
    linewidth=2
)

x = ax.lines[0].get_xdata()
y = ax.lines[0].get_ydata()

plt.fill_between(x, y, alpha=0.1)

plt.xlabel('Review Rating')
plt.title('Distribution of Review Ratings (KDE)')

plt.show()

# KDE before removing missing values
dataset['Review Rating'].plot(
    kind='kde',
    linewidth=2,
    color='blue',
    label='Before Removal'
)

# Create cleaned dataset
dataset_clean = dataset.dropna(subset=['Review Rating'])

# KDE after removing missing values
dataset_clean['Review Rating'].plot(
    kind='kde',
    linewidth=2,
    color='red',
    label='After Removal'
)

plt.xlabel('Review Rating')
plt.title('KDE Plot of Review Rating Before vs After Removal')

plt.legend()

plt.show()

#  the brand max customer belongs to a middle aged group.
plt.figure(figsize=(10,6))

sns.histplot(
    data=cleaned_dataset,
    x='Age',
    bins=15,
    kde=True
)

plt.title('Age Distribution of Customers')
plt.xlabel('Age')
plt.ylabel('Number of Customers')

plt.show()

# converting the biweekly to fortnightly for simplicity
cleaned_dataset['Frequency of Purchases'] = cleaned_dataset[
    'Frequency of Purchases'
].replace({
    'Bi-Weekly':'Fortnightly',
    'Every 3 Months': 'Quarterly'
})
cleaned_dataset.head()

# removing duplicated promo and discount columns as they are identical
pd.crosstab(
    cleaned_dataset['Promo Code Used'],
    cleaned_dataset['Discount Applied']
)

cleaned_dataset['Promotion Used'] = (
    cleaned_dataset['Promo Code Used']
    .map({'Yes':1, 'No':0})
)
cleaned_dataset.drop(
    columns=['Discount Applied'],
    inplace=True
)

"""**cleaned dataset import,importing for hypothesis test **"""

cleaned_dataset.to_csv('cleaned_dataset.csv', index=False)

# now since the data is very much cleaned and replaced null values
# feature construction-
# feature necessary for understanding the core values of the business
# they are-
  # loyal customers columns-based on frequency of purchase , with a definate no of purchase
  # data looks like order placed convert it into like each customer record of order

print(cleaned_dataset['Previous Purchases'].describe())
print(cleaned_dataset['Review Rating'].describe())

"""# Loyalty and customer loyalty category
**Attribute(feature) important for loyalty(with decreasing importance)**

1.   prev purchase-

*   because it tells you the whole tenure of the purchase history of the customer.
*   provide us with the max contribution of each customer to sales.
*   it is normally distributed acoss the range(1,50)
     with mean=25.340668 and median=25

2.   frequency of purchase-


*   used because it explain how offently does a customer purchase from the brand,hence a strong indicator of brand loyalty
*   used actual inverse values of dates to display the actual weightness in the duration.
*   'Weekly': 7

    'Fortnightly': 14

    'Monthly': 30

    'Quarterly': 90

    'Annually': 365






3.   review rating-


*   could have been a strong indicator but the spread is uneven,and display the satisfaction of each customer.
*   its a single transactional information hence not given a wide weightage


4.   subscription-


*   a strong indiaction of brand loyalty and trust in brand awareness.
*   converted to flag of zero and one



---


*   every feature is normalized to reduce scatterness of data points and variance.
*  other factors like discount and promo code is not utilise as they are only defined for a single transctional information









"""

# every days is assigned its weights
frequency_days = {
    'Weekly': 7,
    'Fortnightly': 14,
    'Monthly': 30,
    'Quarterly': 90,
    'Annually': 365
}
cleaned_dataset['Days Between Purchases'] = (
    cleaned_dataset['Frequency of Purchases']
    .map(frequency_days)
)
cleaned_dataset['Frequency Engagement'] = (
    1 /
    cleaned_dataset['Days Between Purchases']
)

# subscription flag is added and normalizing
cleaned_dataset['Subscription Flag'] = (
    cleaned_dataset['Subscription Status']
    .map({
        'Yes': 1,
        'No': 0
    })
)
scaler = MinMaxScaler()
cleaned_dataset[
    [
        'Previous Purchases Norm',
        'Frequency Engagement Norm',
        'Review Rating Norm'
    ]
] = scaler.fit_transform(
    cleaned_dataset[
        [
            'Previous Purchases',
            'Frequency Engagement',
            'Review Rating'
        ]
    ]
)

# loyalty score and segments
cleaned_dataset['Loyalty Score'] = (
      0.50*cleaned_dataset['Previous Purchases Norm'] + 0.25*cleaned_dataset['Frequency Engagement Norm'] + 0.15*cleaned_dataset['Review Rating Norm'] + 0.10*cleaned_dataset['Subscription Flag']

)

q20 = cleaned_dataset['Loyalty Score'].quantile(0.20)
q60 = cleaned_dataset['Loyalty Score'].quantile(0.60)
q80 = cleaned_dataset['Loyalty Score'].quantile(0.80)
def loyalty_segment(score):
    if score >= q80:
        return 'Champion'
    elif score >= q60:
        return 'Loyal'
    elif score >= q20:
        return 'Regular'
    else:
        return 'At Risk'
cleaned_dataset['Customer Loyalty Type'] = (
    cleaned_dataset['Loyalty Score']
    .apply(loyalty_segment)
)

cleaned_dataset.head()

plt.figure(figsize=(10,6))
sns.histplot(
    cleaned_dataset['Loyalty Score'],
    bins=30,
    kde=True
)
plt.title('Distribution of Loyalty Score')
plt.xlabel('Loyalty Score')
plt.ylabel('Number of Customers')
plt.show()

"""# customer value and categorical importance


1.   customer value(adding more value to the brand)


*   purchase value-this gives the purchasing capability of the customer,hence an important indicator to estimate the importance of the customer to profit.
*   subscription- with the high purchase value in compliment to subscription enable the brand to chanelise these customer as potential customer for brand financial growth

problem-
*   loyalty itself summarizes the retention adding customer which are byfar a addition to profit for the brand.
*   considering a prev purchases may result in the redndancy of the data creating a problem with autenticity and also will assign value to more loyal customers rather then displaying the brand about the potential growth of the different customers.

2. with loyalty score and value score


*   we can create differnt customer segmentations like-

          

  *   List item
  *   List item




    





"""

# # checking whether purchase value follow normality
print(cleaned_dataset['Purchase Amount (USD)'].describe())
# correlation between the two feature indicate that they contribute individually to determine each customer value without overwriting anything
print(cleaned_dataset['Previous Purchases'].corr(cleaned_dataset['Subscription Flag']))

# scaling the values
scaler = MinMaxScaler()
cleaned_dataset['Purchase Amount Norm'] = scaler.fit_transform(
    cleaned_dataset[['Purchase Amount (USD)']]
)

# customer value calc
cleaned_dataset['Customer Value Score'] = (
    0.80 * cleaned_dataset['Purchase Amount Norm']
    +
    0.20 * cleaned_dataset['Subscription Flag']
)

high_cutoff = cleaned_dataset[
    'Customer Value Score'
].quantile(0.80)

medium_cutoff = cleaned_dataset[
    'Customer Value Score'
].quantile(0.40)

def assign_value_tier(score):

    if score >= high_cutoff:
        return 'High Value'

    elif score >= medium_cutoff:
        return 'Medium Value'

    else:
        return 'Low Value'

cleaned_dataset['Customer Value Tier'] = (

    cleaned_dataset['Customer Value Score']
    .apply(assign_value_tier)

)

# matrix for loyal score and value score and visual
loyalty_value_matrix = pd.crosstab(
    cleaned_dataset['Customer Loyalty Type'],
    cleaned_dataset['Customer Value Tier']
)
print(loyalty_value_matrix)

plt.figure(figsize=(8, 6))
sns.heatmap(
    loyalty_value_matrix,
    annot=True,
    fmt='d'
)
plt.title('Customer Loyalty vs Value Matrix')
plt.ylabel('Customer Loyalty Type')
plt.xlabel('Customer Value Tier')
plt.show()

"""# Analysis on Ideal Customer


1.   for our consideration an ideal customer is-

    highly loyal + highly valuable
2.   Hence for idealising a true customer we need only champion customers and high value customers


"""

# Create Ideal Customer Flag
cleaned_dataset['Ideal Customer'] = np.where(
    (cleaned_dataset['Customer Loyalty Type'] == 'Champion') &
    (cleaned_dataset['Customer Value Tier'] == 'High Value'),
    'Ideal Customer',
    'Other Customer'
)
print(
    cleaned_dataset['Ideal Customer']
    .value_counts()
)

# profile of ideal customer
ideal_profile = cleaned_dataset.groupby(
    'Ideal Customer'
).agg({
    'Age':'mean',
    'Previous Purchases':'mean',
    'Purchase Amount (USD)':'mean',
    'Review Rating':'mean',
    'Loyalty Score':'mean',
    'Customer Value Score':'mean'
}).round(2)
print(ideal_profile)

# analysis of each feature age,gender,frequency,subscription,geography
# age
age_bins = [18,25,35,45,55,65,100]
age_labels = [
    '18-25',
    '26-35',
    '36-45',
    '46-55',
    '56-65',
    '65+'
]
cleaned_dataset['Age Group'] = pd.cut(
    cleaned_dataset['Age'],
    bins=age_bins,
    labels=age_labels
)
icp_age = (
    cleaned_dataset[
        cleaned_dataset['Ideal Customer']
        == 'Ideal Customer'
    ]
    ['Age Group']
    .value_counts()
    .sort_index()
)
print(icp_age)
plt.figure(figsize=(8,5))
icp_age.plot(kind='bar')
plt.title(
    'Age Distribution of Ideal Customers'
)
plt.ylabel('Number of Customers')
plt.show()

# gender
icp_gender = pd.crosstab(
    cleaned_dataset['Gender'],
    cleaned_dataset['Ideal Customer']
)
print(icp_gender)

# subscription
subscription_rate = (
    cleaned_dataset.groupby(
        'Ideal Customer'
    )['Subscription Flag']
    .mean()
    * 100
)
print(subscription_rate)

# frequency
freq_analysis = (
    cleaned_dataset[
        cleaned_dataset['Ideal Customer']
        == 'Ideal Customer'
    ]
    ['Frequency of Purchases']
    .value_counts()
)
print(freq_analysis)

# location
top_locations = (
    cleaned_dataset[
        cleaned_dataset['Ideal Customer']
        == 'Ideal Customer'
    ]
    ['Location']
    .value_counts()
    .head(10)
)
print(top_locations)

"""# Ideal customer-
A male customer with age group of 46-55(mid aged people) from illinois/arizona,having subscription and frequency of purchase is fortnightly,avg purchase value is  88.93,and total of prev purchases equal to 40.50,and providing an average rating of 3.99,highly interested in clothing.

# Category analysis


1.   Since for the given dataset we have only one entry for each customer,hence practically defining preference of each customer and which category is largely prefer is practically impossible,but based on single purchase we can identify non condlusively which type of customer which product.
2.   we are using LOYALTY SCORE And CATEGORY,to define what is preferred by champion and other customers
"""

# category with customer loyalty - tells you which category purchase what more
category_loyalty = pd.crosstab(
    cleaned_dataset['Category'],
    cleaned_dataset['Customer Loyalty Type']
)

print(category_loyalty)

plt.figure(figsize=(10,6))

sns.heatmap(
    category_loyalty,
    annot=True,
    fmt='d'
)

plt.title('Category vs Loyalty Segment')

plt.show()

# avg loyalty score for each category- how a category attract the customer loyalty
# almost same for each category ,indicating category attraction and pull is slightly greater for footwear
category_loyalty_score = (

    cleaned_dataset
    .groupby('Category')['Loyalty Score']
    .mean()
    .sort_values(ascending=False)

)

print(category_loyalty_score)

# which category attract more valuable customer-in our case accessories attract hgh value customer
category_value = pd.crosstab(
    cleaned_dataset['Category'],
    cleaned_dataset['Customer Value Tier']
)
print(category_value)

# category pull for valuable customer is indicated by avg value score for each category
# in our case footwear attract more valuable customer across all range
category_value_score = (
    cleaned_dataset
    .groupby('Category')['Customer Value Score']
    .mean()
    .sort_values(ascending=False)
)
print(category_value_score)

# merging of both loyalty and valuable customer for brand is more important to understand trend in the each category
# for brand we are require to have both a loyal attracted category and high valued generating category to define performance for each category
category_quality = (
    cleaned_dataset
    .groupby('Category')
    .agg({
        'Loyalty Score':'mean',
        'Customer Value Score':'mean'
    })
)
category_quality['Category Quality Score'] = (
    category_quality['Loyalty Score']
    +
    category_quality['Customer Value Score']
) / 2
category_quality = category_quality.sort_values(
    'Category Quality Score',
    ascending=False
)
print(category_quality)

# category preference amoung ideal customer is
ideal_categories = (
    cleaned_dataset[
        cleaned_dataset['Ideal Customer']
        == 'Ideal Customer'
    ]
    ['Category']
    .value_counts()
)
print(ideal_categories)

"""# Conclusion
for the brand the most loyal and valuable generating customer category in descreasing preference is-


*   Footwear
*  Accessories
*   Clothing
*   Outerwear

ideal customer are more preferring clothing as a category.

# Promotional Analysis


1.   since in the data we have promotion and discount used just for this order,and hence not defined for prev orders therefore we cannot conclusively state whether a customer is completely dependent on pomotion or discount.
2.   there can be many predictions regarded brand introspection of how a brand should focus on promotion and discount


*  category dependency on promotion and discount
*  widely used promo and discount season among all
*   location with high promo and discount uses

**# whether using promotions,discount essentially by brand is attracting a loyal or promotional dependent customers ?**


1.  as mentioned we cannot conclusively say this,but a strong indication of avg(loyal score) with promo and discount uses may indicate a strong creation of loyal customers but this require a correlation between the features.(hypothesis test needed)
"""

# creating a flag for promo and discount
cleaned_dataset['Promo Flag'] = (
    cleaned_dataset['Promo Code Used']
    .map({'Yes':1, 'No':0})
)

# category dependency on promo
promo_category = (
    cleaned_dataset
    .groupby('Category')
    ['Promotion Used']
    .mean()
    * 100
).sort_values(ascending=False)

print(promo_category.round(2))

plt.figure(figsize=(10,5))
promo_category.plot(kind='bar')
plt.ylabel('Promotion Usage (%)')
plt.title('Promotion Usage by Category')
plt.show()

# sesonal dependency on promotions usage
promo_season = (
    cleaned_dataset
    .groupby('Season')
    ['Promotion Used']
    .mean()
    * 100
).sort_values(ascending=False)

print(promo_season.round(2))

# promotion adding any significance to differnet tier of customer
promo_value = pd.crosstab(
    cleaned_dataset['Customer Value Tier'],
    cleaned_dataset['Promo Code Used'],
    normalize='index'
) * 100
print(promo_value.round(2))

# promotion usage spread across loyal customer segments
promo_loyalty = pd.crosstab(
    cleaned_dataset['Customer Loyalty Type'],
    cleaned_dataset['Promo Code Used'],
    normalize='index'
) * 100

print(promo_loyalty.round(2))

plt.figure(figsize=(8,5))
sns.heatmap(
    promo_loyalty,
    annot=True,
    fmt='.1f'
)
plt.title('Promotion Usage Across Loyalty Segments')
plt.show()

# this plot shows how promotions affect the loyalty scores-that is whether promo and discount create a loyalty or not
plt.figure(figsize=(8,5))
sns.boxplot(
    data=cleaned_dataset,
    x='Promo Code Used',
    y='Loyalty Score'
)

plt.title('Loyalty Score by Promotion Usage')
plt.show()

# promo and discount affect on valuable customer score -indicating whether they attract true valuable customers to brand
plt.figure(figsize=(8,5))

sns.boxplot(
    data=cleaned_dataset,
    x='Promo Code Used',
    y='Customer Value Score'
)

plt.title('Customer Value Score by Promotion Usage')
plt.show()

"""# Conclusion
From boxplot and data we can significantly(not conclusively) say that yes promo and discount create a loyal and valuable customer to the brand.



*   category which requires highest promotion to pull customers is - outerwear
*   season which requires highest spends is during-summer and spring

# Geographical analysis

1.   with the location of each order we can derived which loacation does loyal customer segments belongs.
2.   which locations are underutilised and may require promotions and discounts
3.  which location has high purchasing power but low customer retention.
4.  which location has been saturated.
"""

# overall analysis figure for each location
location_analysis = (
    cleaned_dataset
    .groupby('Location')
    .agg({
        'Customer ID':'count',
        'Purchase Amount (USD)':'mean',
        'Previous Purchases':'mean',
        'Loyalty Score':'mean',
        'Customer Value Score':'mean',
        'Subscription Flag':'mean',
        'Promotion Used':'mean'
    })
)
location_analysis.rename(
    columns={
        'Customer ID':'Customer Count',
        'Subscription Flag':'Subscription Rate',
        'Promotion Used':'Promotion Rate'
    },
    inplace=True
)
location_analysis['Subscription Rate'] *= 100
location_analysis['Promotion Rate'] *= 100
location_analysis = location_analysis.round(2)
print(location_analysis)

# location with highest loyal customer/loyal score
top_loyal_locations= (
    location_analysis['Loyalty Score']
    .sort_values(
        ascending=False
    )
    .head(10)
)
print(top_loyal_locations)

# market opportunity score-indicating - highly loyal and valuable customer but less no of custoemr(untapped market)-high potential market
market_data = location_analysis.copy()
scaler = MinMaxScaler()
market_data[
    [
        'Loyalty Norm',
        'Value Norm',
        'Customer Count Norm'
    ]
] = scaler.fit_transform(
    market_data[
        [
            'Loyalty Score',
            'Customer Value Score',
            'Customer Count'
        ]
    ]
)
market_data['Market Opportunity Score'] = (
      0.40 * market_data['Loyalty Norm']
    + 0.40 * market_data['Value Norm']
    + 0.20 * (1 - market_data['Customer Count Norm'])
)
market_data = market_data.sort_values(
    'Market Opportunity Score',
    ascending=False
)
print(
    market_data[
        [
            'Market Opportunity Score'
        ]
    ].head(15)
)


top_markets = (
    market_data
    .head(15)
)
plt.figure(figsize=(12,6))
plt.bar(
    top_markets.index,
    top_markets['Market Opportunity Score']
)
plt.xticks(rotation=45)
plt.title(
    'Top Market Opportunity Locations'
)
plt.ylabel(
    'Opportunity Score'
)
plt.show()

# medium lesser potential markets(underutilised markets)- where loyalty is descent and valuable customer is above average but cusotmer count is less
underutilized_markets = location_analysis[
    (location_analysis['Loyalty Score']
     > location_analysis['Loyalty Score'].mean())
    &
    (location_analysis['Customer Value Score']
     > location_analysis['Customer Value Score'].mean())
    &
    (location_analysis['Customer Count']
     < location_analysis['Customer Count'].mean())
]
print(
    underutilized_markets.sort_values(
        'Loyalty Score',
        ascending=False
    )
)

"""# Conclusion


*   untapped and underutilised markets display two very different potential scales,hence measured differently(example-tennessee underutilised but not untapped market)
*   location like - alaska has high potential customer and high valuable customer but isn't utilised to its max.
*    hawaii has the highest loyal customer segment



"""

cleaned_dataset.to_csv(
    "customer_data_final.csv",
    index=False
)

