# -*- coding: utf-8 -*-
"""hypothesisTesting and feature selection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lGem5jp_wJmXR7WA_dGBzeoecPizPxFn
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

cleaned_dataset=pd.read_csv('/content/customer_data_final (1).csv')

dataset.info()

# finding the relationship if exist between mode of payment and prev purchases and frequency
# as there can be credit bonuses on different payment option
# hence their maybe a significant relation which can be in existence

"""**# since the payment method is multi categorical columns and prev purchases is numerical**
# one way anove is a wise choice to select
"""

# h0=U(prev purchases) not varies with mode of payment
# h1=U(prev purchases) varries with atleast one mode of payment

# significance level is assumed to be alpha=0.05

# limitation of the one test anova is it should have chi square distribution divided with its dof and chi square is square of normal distribution
# therefor we need to have the - normality of data(shapiro wilk test or graphically)
sns.displot(
    data=cleaned_dataset,
    x='Previous Purchases',
    col='Payment Method',
    kde=True,
    col_wrap=3
)

plt.show()

# graph shows no clear indication of normality but since every group conatians element more then 30
# we can stiill use the anova as central limit theorem will converge it into sampling distribution which normal in nature
group_sizes = (
    cleaned_dataset.groupby('Payment Method')
    .size()
    .reset_index(name='Sample Size')
    .sort_values('Sample Size', ascending=False)
)

print(group_sizes)

from scipy.stats import f_oneway

groups = [
    group['Previous Purchases'].values
    for _, group in cleaned_dataset.groupby('Payment Method')
]

f_stat, p_value = f_oneway(*groups)

print("F-statistic:", f_stat)
print("P-value:", p_value)

if p_value < 0.05:
    print("Significant relationship exists")
else:
    print("No significant relationship found")

"""# **now checking the hypothesis test for frequency of purchases and mode of payment**

since the payment method is categorical and frequency of purchases is also categorifcal
contingency table and chi square is best



*   ho=their is no realation between them
*   h1=their is significant relation between them
"""

import pandas as pd

contingency_table = pd.crosstab(
    cleaned_dataset['Payment Method'],
    cleaned_dataset['Frequency of Purchases']
)

print(contingency_table)

# doing cell count for limitation of chi square
from scipy.stats import chi2_contingency

chi2, p, dof, expected = chi2_contingency(
    contingency_table
)

expected_df = pd.DataFrame(
    expected,
    index=contingency_table.index,
    columns=contingency_table.columns
)

print(expected_df.round(2))

# checking if any group contain counts less then 5
((expected < 5).sum() / expected.size) * 100

"""Since none of the count is less then 5 hence we can go out for performin the chi sqaure test

"""

from scipy.stats import chi2_contingency

chi2, p, dof, expected = chi2_contingency(
    contingency_table
)

print("Chi-square Statistic:", chi2)
print("P-value:", p)
print("Degrees of Freedom:", dof)

"""**since the pvalue is more then significane level alpha = 0.05**
we cannot reject the null hypothesis which states that-> # their is no relation between them

# Conclusion-


1.   There is no relation between prev purchase and mode of payment.
2.   There is no relation between prev purchase and frequency of purchases.

# 3)  do subscription effect the loyalty of the customer,means is their any correlation between them ?


1.   h0= mean of loyalty do  have a realtion with subscription
2.   h1=their exits no realtioin between subscription and loyalty


*   since subscription is a categorical column and loyalty is a numerical collumn their for t test can be used.
*   limitation- check for normality of numerical column that is loyalty score.
"""

# normality between the loyalty score
from scipy.stats import shapiro

sample = cleaned_dataset['Loyalty Score'].sample(
    n=500,
    random_state=42
)

stat, p = shapiro(sample)

print("Shapiro Statistic:", stat)
print("P-value:", p)

# since p value is less then 0.05 significance level hence loyalty scoer is normally distributed
print(cleaned_dataset['Subscription Status'].value_counts())
subscribed = cleaned_dataset[
    cleaned_dataset['Subscription Status'] == 'Yes'
]['Loyalty Score']

not_subscribed = cleaned_dataset[
    cleaned_dataset['Subscription Status'] == 'No'
]['Loyalty Score']

from scipy.stats import levene

stat, p = levene(subscribed, not_subscribed)

print("Levene Statistic:", stat)
print("P-value:", p)

# p_value>.05 hence equal variance
from scipy.stats import ttest_ind

t_stat, p_value = ttest_ind(
    subscribed,
    not_subscribed,
    equal_var=False
)

print("T-statistic:", t_stat)
print("P-value:", p_value)

# p value is more then 0.05 hence we cannot reject null hypothesis
# hence their exists a a realtion between subscription and loyalty score

"""# 4) hypthesis test for customer loylaty with category ?


1.   h0=mean of loyalty score is not varrying much
2.   h1=mean of loyalty score is varrying atleast for one category

*   performing one way anova test for categorical and numeical column
*   normality check




"""

# normality check-all pass
from scipy.stats import shapiro

for category in cleaned_dataset['Category'].unique():

    sample = cleaned_dataset[
        cleaned_dataset['Category'] == category
    ]['Customer Value Score']

    sample = sample.sample(
        min(500, len(sample)),
        random_state=42
    )

    stat, p = shapiro(sample)

    print(f"{category}: p = {p:.4f}")

from scipy.stats import f_oneway

groups = [
    grp['Customer Value Score'].values
    for _, grp in cleaned_dataset.groupby('Category')
]

f_stat, p_value = f_oneway(*groups)

print("F-statistic:", f_stat)
print("P-value:", p_value)

# sinve p value is more then significance level 0.05 hence we can reject teh null hypothesis
# means their exist a realtion between category and loyalty score

"""# 5) hyptohesis test between location and loyalty score ?


1.   ho=mean of loyalty score do not varries along loyalty
2.   h1=mean of loyatly varries atleat in one location



*   performing one way annova because of categorical and numerical column
*   normallity test






"""

# normality and homgenity check
location_counts = cleaned_dataset['Location'].value_counts()
valid_locations = location_counts[
    location_counts >= 30
].index

location_df = cleaned_dataset[
    cleaned_dataset['Location'].isin(valid_locations)
]

from scipy.stats import levene

groups = [
    grp['Loyalty Score'].values
    for _, grp in location_df.groupby('Location')
]

stat, p = levene(*groups)

print("Levene Statistic:", stat)
print("P-value:", p)

# since p value is more then significance level that is why the variance between each group is eqaal

# performing test
from scipy.stats import f_oneway

groups = [
    grp['Loyalty Score'].values
    for _, grp in location_df.groupby('Location')
]

f_stat, p_value = f_oneway(*groups)

print("F-statistic:", f_stat)
print("P-value:", p_value)

# since p value is more then 0.05 therefore we can reject null hypothesis
# which state that their exist a realtion between loyalty and location

"""# final correlatioin matrix between loyalty and customer value score and other feature so to identify important feature to conclude"""

features = [
    'Age',
    'Previous Purchases',
    'Review Rating',
    'Loyalty Score',
    'Customer Value Score',
    'Subscribed_Flag'
]

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

corr_cols = [
    'Age',
    'Previous Purchases',
    'Review Rating',
    'Loyalty Score',
    'Customer Value Score'
]

corr_matrix = cleaned_dataset[corr_cols].corr(method='pearson')

plt.figure(figsize=(8,6))

sns.heatmap(
    corr_matrix,
    annot=True,
    cmap='RdYlBu_r',
    fmt='.2f',
    linewidths=0.5
)

plt.title('Correlation Matrix of Customer Metrics')
plt.tight_layout()
plt.show()